name: Deploy Full to POC
on:
  workflow_dispatch: null
  push:
    branches:
      - POC
    paths:
      - force-app/**
jobs:
  deploy-full:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important: Need full history to compare commits
      
      - name: 'Install Salesforce CLI'
        run: npm install -g @salesforce/cli
      
      - name: 'Prepare JWT Key'
        run: echo "${{ secrets.NTSBPOC_SERVER_KEY }}" > server.key
      - name: 'Authenticate'
        run: |
          sf org login jwt \
            --client-id ${{ secrets.NTSBPOC_CONSUMER_KEY }} \
            --jwt-key-file server.key \
            --username ${{ secrets.NTSBPOC_USER_NAME }} \
            --instance-url "${{ vars.NTSBPOC_URL }}" \
            --set-default
      
      # 3. Deploy full content
      - name: 'Deploy full source'
        run: |
          sf project deploy start \
            --source-dir force-app \
            --wait 10 \
            --test-level RunLocalTests
